# Generated by Django 5.0 on 2024-01-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="nick",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
